###############################################################################
# Author: Michael DelGaudio & Sunmin Lee
# Date: 06/24/2020
# Pledge: I pledge my honor that I have abided by the Stevens Honor System.
# Description: MtSieve Makefile
###############################################################################

CC     = gcc
C_FILE = $(wildcard *.c)
TARGET = $(patsubst %.c,%,$(C_FILE))
CFLAGS = -O3 -Wall -Werror -pedantic-errors 

all:
	$(CC) $(CFLAGS) $(C_FILE) -o $(TARGET) -lm -pthread
clean:
	rm -f $(TARGET) $(TARGET).exe